[package]
name = "webcams-multimedia"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.23.5"


[[bin]]
name="video-sender"
path="src/main.rs"

[[bin]]
name="video-receiver"
path="src/receiver.rs"
